// flow-typed signature: 7c88959792182f9243fe1b41193e968d
// flow-typed version: <<STUB>>/graphcool_v^1.3.7/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphcool'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphcool' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphcool/dist/src/api/api' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/api/GraphcoolAuthServer' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/commands/auth' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/commands/clone' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/commands/console' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/commands/delete' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/commands/endpoints' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/commands/export' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/commands/init' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/commands/interactiveInit' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/commands/playground' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/commands/projects' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/commands/pull' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/commands/push' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/commands/quickstart' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/commands/status' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/index' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/system/FileSystemResolver' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/system/StdOut' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/types' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/utils/arguments' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/utils/auth' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/utils/config' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/utils/constants' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/utils/file' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/utils/parseCommand' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/utils/ping' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/utils/system' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/utils/usage' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/utils/utils' {
  declare module.exports: any;
}

declare module 'graphcool/dist/src/utils/validation' {
  declare module.exports: any;
}

declare module 'graphcool/dist/tests/auth.test' {
  declare module.exports: any;
}

declare module 'graphcool/dist/tests/clone.test' {
  declare module.exports: any;
}

declare module 'graphcool/dist/tests/export.test' {
  declare module.exports: any;
}

declare module 'graphcool/dist/tests/fixtures/mock_data' {
  declare module.exports: any;
}

declare module 'graphcool/dist/tests/fixtures/schemas' {
  declare module.exports: any;
}

declare module 'graphcool/dist/tests/helpers/test_argv' {
  declare module.exports: any;
}

declare module 'graphcool/dist/tests/helpers/test_auth_server' {
  declare module.exports: any;
}

declare module 'graphcool/dist/tests/helpers/test_environment' {
  declare module.exports: any;
}

declare module 'graphcool/dist/tests/helpers/test_out' {
  declare module.exports: any;
}

declare module 'graphcool/dist/tests/helpers/test_resolver' {
  declare module.exports: any;
}

declare module 'graphcool/dist/tests/init.test' {
  declare module.exports: any;
}

declare module 'graphcool/dist/tests/parseCommand.test' {
  declare module.exports: any;
}

declare module 'graphcool/dist/tests/pull.test' {
  declare module.exports: any;
}

declare module 'graphcool/dist/tests/push.test' {
  declare module.exports: any;
}

declare module 'graphcool/dist/tests/utils_config.test' {
  declare module.exports: any;
}

declare module 'graphcool/dist/tests/utils_file.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphcool/dist/src/api/api.js' {
  declare module.exports: $Exports<'graphcool/dist/src/api/api'>;
}
declare module 'graphcool/dist/src/api/GraphcoolAuthServer.js' {
  declare module.exports: $Exports<'graphcool/dist/src/api/GraphcoolAuthServer'>;
}
declare module 'graphcool/dist/src/commands/auth.js' {
  declare module.exports: $Exports<'graphcool/dist/src/commands/auth'>;
}
declare module 'graphcool/dist/src/commands/clone.js' {
  declare module.exports: $Exports<'graphcool/dist/src/commands/clone'>;
}
declare module 'graphcool/dist/src/commands/console.js' {
  declare module.exports: $Exports<'graphcool/dist/src/commands/console'>;
}
declare module 'graphcool/dist/src/commands/delete.js' {
  declare module.exports: $Exports<'graphcool/dist/src/commands/delete'>;
}
declare module 'graphcool/dist/src/commands/endpoints.js' {
  declare module.exports: $Exports<'graphcool/dist/src/commands/endpoints'>;
}
declare module 'graphcool/dist/src/commands/export.js' {
  declare module.exports: $Exports<'graphcool/dist/src/commands/export'>;
}
declare module 'graphcool/dist/src/commands/init.js' {
  declare module.exports: $Exports<'graphcool/dist/src/commands/init'>;
}
declare module 'graphcool/dist/src/commands/interactiveInit.js' {
  declare module.exports: $Exports<'graphcool/dist/src/commands/interactiveInit'>;
}
declare module 'graphcool/dist/src/commands/playground.js' {
  declare module.exports: $Exports<'graphcool/dist/src/commands/playground'>;
}
declare module 'graphcool/dist/src/commands/projects.js' {
  declare module.exports: $Exports<'graphcool/dist/src/commands/projects'>;
}
declare module 'graphcool/dist/src/commands/pull.js' {
  declare module.exports: $Exports<'graphcool/dist/src/commands/pull'>;
}
declare module 'graphcool/dist/src/commands/push.js' {
  declare module.exports: $Exports<'graphcool/dist/src/commands/push'>;
}
declare module 'graphcool/dist/src/commands/quickstart.js' {
  declare module.exports: $Exports<'graphcool/dist/src/commands/quickstart'>;
}
declare module 'graphcool/dist/src/commands/status.js' {
  declare module.exports: $Exports<'graphcool/dist/src/commands/status'>;
}
declare module 'graphcool/dist/src/index.js' {
  declare module.exports: $Exports<'graphcool/dist/src/index'>;
}
declare module 'graphcool/dist/src/system/FileSystemResolver.js' {
  declare module.exports: $Exports<'graphcool/dist/src/system/FileSystemResolver'>;
}
declare module 'graphcool/dist/src/system/StdOut.js' {
  declare module.exports: $Exports<'graphcool/dist/src/system/StdOut'>;
}
declare module 'graphcool/dist/src/types.js' {
  declare module.exports: $Exports<'graphcool/dist/src/types'>;
}
declare module 'graphcool/dist/src/utils/arguments.js' {
  declare module.exports: $Exports<'graphcool/dist/src/utils/arguments'>;
}
declare module 'graphcool/dist/src/utils/auth.js' {
  declare module.exports: $Exports<'graphcool/dist/src/utils/auth'>;
}
declare module 'graphcool/dist/src/utils/config.js' {
  declare module.exports: $Exports<'graphcool/dist/src/utils/config'>;
}
declare module 'graphcool/dist/src/utils/constants.js' {
  declare module.exports: $Exports<'graphcool/dist/src/utils/constants'>;
}
declare module 'graphcool/dist/src/utils/file.js' {
  declare module.exports: $Exports<'graphcool/dist/src/utils/file'>;
}
declare module 'graphcool/dist/src/utils/parseCommand.js' {
  declare module.exports: $Exports<'graphcool/dist/src/utils/parseCommand'>;
}
declare module 'graphcool/dist/src/utils/ping.js' {
  declare module.exports: $Exports<'graphcool/dist/src/utils/ping'>;
}
declare module 'graphcool/dist/src/utils/system.js' {
  declare module.exports: $Exports<'graphcool/dist/src/utils/system'>;
}
declare module 'graphcool/dist/src/utils/usage.js' {
  declare module.exports: $Exports<'graphcool/dist/src/utils/usage'>;
}
declare module 'graphcool/dist/src/utils/utils.js' {
  declare module.exports: $Exports<'graphcool/dist/src/utils/utils'>;
}
declare module 'graphcool/dist/src/utils/validation.js' {
  declare module.exports: $Exports<'graphcool/dist/src/utils/validation'>;
}
declare module 'graphcool/dist/tests/auth.test.js' {
  declare module.exports: $Exports<'graphcool/dist/tests/auth.test'>;
}
declare module 'graphcool/dist/tests/clone.test.js' {
  declare module.exports: $Exports<'graphcool/dist/tests/clone.test'>;
}
declare module 'graphcool/dist/tests/export.test.js' {
  declare module.exports: $Exports<'graphcool/dist/tests/export.test'>;
}
declare module 'graphcool/dist/tests/fixtures/mock_data.js' {
  declare module.exports: $Exports<'graphcool/dist/tests/fixtures/mock_data'>;
}
declare module 'graphcool/dist/tests/fixtures/schemas.js' {
  declare module.exports: $Exports<'graphcool/dist/tests/fixtures/schemas'>;
}
declare module 'graphcool/dist/tests/helpers/test_argv.js' {
  declare module.exports: $Exports<'graphcool/dist/tests/helpers/test_argv'>;
}
declare module 'graphcool/dist/tests/helpers/test_auth_server.js' {
  declare module.exports: $Exports<'graphcool/dist/tests/helpers/test_auth_server'>;
}
declare module 'graphcool/dist/tests/helpers/test_environment.js' {
  declare module.exports: $Exports<'graphcool/dist/tests/helpers/test_environment'>;
}
declare module 'graphcool/dist/tests/helpers/test_out.js' {
  declare module.exports: $Exports<'graphcool/dist/tests/helpers/test_out'>;
}
declare module 'graphcool/dist/tests/helpers/test_resolver.js' {
  declare module.exports: $Exports<'graphcool/dist/tests/helpers/test_resolver'>;
}
declare module 'graphcool/dist/tests/init.test.js' {
  declare module.exports: $Exports<'graphcool/dist/tests/init.test'>;
}
declare module 'graphcool/dist/tests/parseCommand.test.js' {
  declare module.exports: $Exports<'graphcool/dist/tests/parseCommand.test'>;
}
declare module 'graphcool/dist/tests/pull.test.js' {
  declare module.exports: $Exports<'graphcool/dist/tests/pull.test'>;
}
declare module 'graphcool/dist/tests/push.test.js' {
  declare module.exports: $Exports<'graphcool/dist/tests/push.test'>;
}
declare module 'graphcool/dist/tests/utils_config.test.js' {
  declare module.exports: $Exports<'graphcool/dist/tests/utils_config.test'>;
}
declare module 'graphcool/dist/tests/utils_file.test.js' {
  declare module.exports: $Exports<'graphcool/dist/tests/utils_file.test'>;
}
